port 26383
bind 127.0.0.1
protected-mode no
sentinel monitor redis-production 127.0.0.1 16381 2
sentinel down-after-milliseconds redis-production 2000
sentinel failover-timeout redis-production 10000
sentinel parallel-syncs redis-production 1

